inventory/urls.py
# -*- coding: utf-8 -*-
# import our django dependencies
from django.conf.urls import url
from django_filters.views import FilterView

# import our views and filters
from inventory import views

# configure our app name
app_name = 'inventory'

# set our url patterns
urlpatterns = [
    # /inventory/
    url(r'^$', views.index, name='inventory'),

    # /inventory/checkin/
    url(r'^checkin/$', views.checkin, name='checkin'),

    # /inventory/import/
    url(r'^import/$', views.file_upload, name='file_upload'),

    # /inventory/badupload/
    url(r'^badupload/$', views.badupload, name='badupload'),

    # /inventory/search/
    url(r'^search/$', views.search, name='search'),

    # /inventory/lotspace
    url(r'^lotspace/$', views.lotspace, name='lotspace'),

    # /inventory/detail/<vin>/
    url(r'^detail/(?P<vin>[\w-]+)$', views.detail, name='detail'),

    # /inventory/payment/
    url(r'^payment/$', views.payment, name='payment'),

    # /inventory/payment/<vin>/
    url(r'^payment/(?P<vin>[\w-]+)$', views.payment, name='payment'),
]

t5towing/urls.py
# -*- coding: utf-8 -*-
# import our django dependencies
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

# import our views and forms
from inventory import views
from inventory.forms import LoginForm

# configure our app name
app_name = 't5towing'

# set our url patterns
urlpatterns = [
    # /
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),

    # /inventory/
    url(r'^inventory/', include ('inventory.urls'), name='inventory'),

    # /admin/
    url(r'^admin/', admin.site.urls),

    # /register/
    url(r'^register/$', views.registration, name='registration'),

    # /login/
    url(r'^login/', auth_views.login, {'template_name': 't5towing/login.html', 'authentication_form': LoginForm}, name='login'),

    # /logout/
    url(r'^logout/', auth_views.logout, {'template_name': 't5towing/logout.html'}, name='logout'),

    # /metrics
    url(r'^metrics/$', views.metrics, name='metrics'),

    # /paymentsummary/
    url(r'^payment_summary/$', views.payment_summary, name='payment_summary'),

    # /profile/<username>
    url(r'^profile/$', views.profile, name='profile'),
]

inventory/forms.py
# -*- coding: utf-8 -*-
# import our django dependencies
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Max
from django.forms import ModelChoiceField

# import our models and functions
from inventory.models import *
from inventory.utils import get_empty_lotspaces

# datepicker form to handle start and end dates for metrics
class DatePickerForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

# employee form that handles displaying profile details. this is linked to the employee model.
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

# login form to handle authentication. we use widget attributes to further
# define corresponding form fields
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username', 'placeholder': 'Username'}))
    password = forms.CharField(label="Password", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password', 'placeholder': 'Password', 'type': 'password'}))

# lotspace model form that we use for vehicle check-in page. we define its __init__
# so that we can limit the contents of the 'number' drop down list to only
# empty lotspaces. this is linked to the lotspace model.
class LotSpaceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(LotSpaceForm, self).__init__(*args, **kwargs)
        self.fields['number'] = forms.ChoiceField(get_empty_lotspaces(), required=False, widget=forms.Select())
    class Meta:
        model = LotSpace
        fields = '__all__'

# payment form that handles payments. this is linked to the payment model.
class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'

# registration form that handles new user registration. this form is linked
# to the built-in django user account, which is in turn replicated across to
# the employee model. we use widget attributes to specify additional form
# parameters
class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'first_name', 'placeholder': 'Your First Name'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'last_name', 'placeholder': 'Your Last Name'}))
    address = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'address', 'placeholder': 'Your Physical Address'}))
    phone = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username', 'placeholder': '(555)555-5555'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'address', 'phone', 'username', 'password1', 'password2')
        widgets = {
            'username' : forms.TextInput(attrs = {'class': 'form-control', 'name': 'username', 'placeholder': 'Username'}),
            'password1' : forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': 'Password'}),
            'password2' : forms.PasswordInput(attrs = {'class': 'form-control', 'placeholder': 'Required. Re-type your password'}),
        }

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

# simple lotspace form. this is linked to the lotspace model.
class SimpleLotSpaceForm(forms.ModelForm):
    class Meta:
        model = LotSpace
        fields = ('number',)

# towtrip form used to post and get towtrip details. this is linked to the
# towtrip model.
class TowTripForm(forms.ModelForm):
    class Meta:
        model = TowTrip
        fields = '__all__'

# uploadfile form used to handle file uploads
class UploadFileForm(forms.Form):
    file = forms.FileField()

# vehicle form that handles vehicle data. this is linked to the vehicle model.
class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = '__all__'

inventory/views.py
# -*- coding: utf-8 -*-
# import our python dependencies
from __future__ import unicode_literals
import datetime
import re
from decimal import Decimal

# import our django dependencies
from django import forms
from django.contrib import messages
from django.contrib.auth import login as auth_login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Max
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone

# import the graphos graphing library
from graphos.sources.model import ModelDataSource
from graphos.renderers.gchart import ColumnChart

# import all of our custom filters, forms, functions, and models
from inventory.filters import LotSpaceFilter, PaymentFilter, VehicleFilter
from inventory.forms import DatePickerForm, EmployeeForm, LoginForm, LotSpaceForm, PaymentForm, PaymentMetrics, RegistrationForm, TowTripForm, TowTripMetrics, VehicleForm, SimpleLotSpaceForm, UploadFileForm
from inventory.models import LotSpace, Payment, TowTrip, Vehicle
from inventory.utils import import_csv_to_model, calculate_vehicle_balance, vehicle_check_out

# bad file upload error page
# this view displays an error page if there is a problem uploading a file
@login_required(login_url="/login")
def badupload(request):
    return HttpResponse('There was a problem with your upload')

# vehicle check-in
# this view takes all of the input fields, copies/assigns them to their
# appropriate form, and then saves the associated objects to the database
@login_required(login_url="/login")
def checkin(request):
    if request.POST:
        # because request.POST is immutable, we make a copy of it and modify
        # it as needed before we copy the modified contents back into the
        # request.POST. In this case, we are copying around form entries
        # in order to complete the necessary form entries for all three forms:
        # vehicle, towtrip, and lotspace
        post_copy = request.POST.copy()
        post_copy['towtrip-vehicle'] = post_copy['vehicle-vin']
        post_copy['lotspace-towtrip'] = post_copy['towtrip-timestamp']
        post_copy['vehicle-checkedin'] = True
        post_copy['lotspace-full'] = True
        post_copy['lotspace-timestamp'] = timezone.now()
        post_copy['vehicle-balance'] = '0.00'
        request.POST = post_copy

        # assign vehicle to this check-in if it already exists, otherwise
        # create a new entry
        try:
            vehicle = Vehicle.objects.get(vin=request.POST['vehicle-vin'])
            vehicle_form = VehicleForm(instance=vehicle)
        except Vehicle.DoesNotExist:
            vehicle_form = VehicleForm(request.POST, prefix="vehicle")

        # save vehicle_form and then refresh from database if form is valid
        if vehicle_form.is_valid():
            vehicle = vehicle_form.save()
            vehicle.refresh_from_db()
            towtrip_form = TowTripForm(request.POST, prefix="towtrip")

            # save towtrip_form and then refresh from database if form is valid
            if towtrip_form.is_valid():
                towtrip = towtrip_form.save()
                towtrip.refresh_from_db()

                # every time a towtrip is added, we take note of the date
                # and add a tally to the number of tows for that date
                timestamp = towtrip_form.cleaned_data['timestamp']
                try:
                    towtrip_metrics = TowTripMetrics.objects.get(date=timestamp.date())
                except TowTripMetrics.DoesNotExist:
                    towtrip_metrics = TowTripMetrics.objects.create(date=timestamp.date(), number_of_tows=0)
                towtrip_metrics.number_of_tows += 1
                towtrip_metrics.save()
                # save lotspace_form and then refresh from database if form is valid
                lotspace_form = LotSpaceForm(request.POST, prefix="lotspace")

                if lotspace_form.is_valid():
                    lotspace = lotspace_form.save()
                    lotspace.refresh_from_db()
                    messages.success(request, 'Your vehicle has been successfully checked in to the system!')
                else:
                    messages.error(request, 'Your lot space form is invalid!')
            else:
                messages.error(request, 'Your tow trip form is invalid!')
        else:
            messages.error(request, 'Your vehicle form is invalid!')

        return redirect('inventory:checkin')
    else:
        vehicle_form = VehicleForm(prefix='vehicle')
        towtrip_form = TowTripForm(prefix='towtrip')
        lotspace_form = LotSpaceForm(prefix='lotspace')

    return render(request, 'inventory/checkin.html', {'vehicle_form': vehicle_form, 'towtrip_form': towtrip_form, 'lotspace_form': lotspace_form})

# vehicle detail
# for every vehicle, this detail view displays vehicle, latest towtrip, and
# lotspace details
def detail(request, vin):
    calculate_vehicle_balance(vin)
    vehicle = Vehicle.objects.get(vin=vin)
    towtrip = TowTrip.objects.filter(vehicle=vin).latest('timestamp')
    vehicle_form = VehicleForm(instance=vehicle)
    towtrip_form = TowTripForm(instance=towtrip)

    if vehicle.checkedin == True:
        lotspace = LotSpace.objects.get(towtrip=towtrip.timestamp)
        lotspace_form = SimpleLotSpaceForm(instance=lotspace)
    else:
        lotspace_form = SimpleLotSpaceForm()

    # if the logged-in user submits a checkout request, we run the checkout
    # function
    if request.POST:
        checkout = vehicle_check_out(request, vin)
        return redirect('inventory:detail', vin=vin)

    return render(request, 'inventory/detail.html', {'vin': vin, 'vehicle_form': vehicle_form, 'towtrip_form': towtrip_form, 'lotspace_form': lotspace_form})

# upload csv files
# this view takes an input file and assigns it to the UploadFileForm form.
# if valid, the UploadFileForm is processed by the utils.import_csv_to_model
# function in order to add the csv data to the database
@login_required(login_url="/login")
def file_upload(request):
    if request.POST and request.FILES:
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            rawcsv = import_csv_to_model(request.FILES['file'])
            messages.success(request, 'Your file was uploaded successfully!')
            return redirect('inventory:file_upload')
        else:
            return redirect('inventory:badupload')
    else:
        form = UploadFileForm()
    return render(request, 'inventory/import.html', {'form': form})

# login
# this view processes login requests
def login(request):
    if request.POST:
        form = LoginForm(request.POST)
        return render(request, 't5towing/login.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 't5towing/login.html', {'form': form})

# root homepage
def index(request):
    return redirect('home')

# lotspace capacity
# this view goes through all the lotspace data to find the latest state of
# of every lotspace. It then populates a set of meters that indicate how full
# the lot is
@login_required(login_url="/login")
def lotspace(request):
    # initialize our variables
    lotspace_sections = ['A','B','C','D']
    perm_lotspace_list = []
    temp_lotspace_list = []
    full_a_count = 0
    full_b_count = 0
    full_c_count = 0
    full_d_count = 0

    # Collect the latest record for every lot space
    for section in lotspace_sections:
        temp_lotspace_list = []
        for x in range(1,251):
            str_x = str(x).zfill(3)
            temp_lotspace_list.append(LotSpace.objects.filter(number=section + str_x).latest('towtrip'))
            perm_lotspace_list.append(LotSpace.objects.filter(number=section + str_x).latest('towtrip'))

        # keep tally when lotspaces are full
        for space in temp_lotspace_list:
            if space.full == True:
                if section == 'A':
                    full_a_count += 1
                if section == 'B':
                    full_b_count += 1
                if section == 'C':
                    full_c_count += 1
                if section == 'D':
                    full_d_count += 1

    # generate the variables we will pass to the html page
    full_a_count = float(full_a_count)
    total_a_count = float(len(temp_lotspace_list))
    fraction_a_full = float(full_a_count/total_a_count)
    percent_a_full = int(fraction_a_full*100)

    full_b_count = float(full_b_count)
    total_b_count = float(len(temp_lotspace_list))
    fraction_b_full = float(full_b_count/total_b_count)
    percent_b_full = int(fraction_b_full*100)

    full_c_count = float(full_c_count)
    total_c_count = float(len(temp_lotspace_list))
    fraction_c_full = float(full_c_count/total_c_count)
    percent_c_full = int(fraction_c_full*100)

    full_d_count = float(full_d_count)
    total_d_count = float(len(temp_lotspace_list))
    fraction_d_full = float(full_d_count/total_d_count)
    percent_d_full = int(fraction_d_full*100)

    # generate the filter data that will populate the lotspace table
    #all_lotspaces = LotSpace.objects.all()
    #all_lotspaces = LotSpace.objects.values('number', 'full', 'timestamp').annotate(latest_record=Max('timestamp')).order_by('number')
    #lotspace_filter = LotSpaceFilter(request.GET, queryset=all_lotspaces)
    return render(request, 'inventory/lotspace.html', {'lotspace_list': perm_lotspace_list, 'lotspace_a_percent': percent_a_full, 'lotspace_b_percent': percent_b_full, 'lotspace_c_percent': percent_c_full, 'lotspace_d_percent': percent_d_full})

# metrics
# this view displays a graph of towtrip frequency for the dates chosen from
# the datepicker. By default, it shows all of the data.
@login_required(login_url="/login")
def metrics(request):
    # if the user inputs a start and end date, the graph will show only

inventory/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "meta.html" %}
    <link rel="icon" href="{% static "inventory/favicon.ico" %}">
    <title>T5 Towing Application</title>
    {% include "bootstrapcss.html" %}
    {% include "googlechartjs.html" %}
    {% include "datepickercss.html" %}
    {% include "datepickerjs.html" %}
    {% include "datepickerscript.html" %}
  </head>
  <body>
    {% include "navbar.html" %}
    <div class="container theme-showcase" role="main">
        {% block content %}{% endblock %}
    </div>
    {% include "bootstrapjs.html" %}
  </body>
</html>

inventory/templates/bootstrapcss.html
{% load static %}
<!-- Bootstrap core CSS -->
<link href="{% static "inventory/dist/css/bootstrap.min.css" %}" rel="stylesheet">
<!-- Bootstrap theme -->
<link href="{% static "inventory/dist/css/bootstrap-theme.min.css" %}" rel="stylesheet">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="{% static "inventory/assets/css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">
<!-- jquery library for notification bars at top -->
<link href="{% static "inventory/dist/css/jquery.messagebar.min.css" %}" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static "inventory/theme.css" %}" rel="stylesheet">
<!-- Circle percentage bar -->
<link href="{% static "inventory/dist/css/circle.css" %}" rel="stylesheet" >

inventory/templates/bootstrapjs.html
{% load static %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static "inventory/assets/js/vendor/jquery.min.js" %}"><\/script>')</script>
<script src="{% static "inventory/dist/js/bootstrap.min.js" %}"></script>
<script src="{% static "inventory/assets/js/docs.min.js" %}"></script>
<!-- jquery library for notification bars at top -->
<script src="{% static "inventory/dist/js/jquery.messagebar.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static "inventory/assets/js/ie10-viewport-bug-workaround.js" %}"></script>

inventory/templates/datepickercss.html
<!-- DatePicker CSS -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">

inventory/templates/datepickerjs.html
<!-- DatePicker JS -->
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

inventory/templates/datepickerscript.html
<!-- DatePicker script -->
<script>
$( function() {
  $( "#datepicker" ).datepicker();
} );
</script>

inventory/templates/googlechartjs.html
<!-- GChart JS -->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
</script>

inventory/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container theme-showcase" role="main">
  <div class="jumbotron">
  <h1>T5 Towing</h1>
  <h3>Welcome to the T5 Towing Website</h3>
  <br>
  <p>Please use the Search link above to search for and confirm that your vehicle is located in the T5 Towing lot.</p>
  <br>
  <p>If your car has been towed by T5 Towing, please note the following information:</p>
  <ul>
    <li><p>The daily rate is $50 and will be charged so long as your vehicle is in the lot.</p></li>
    <li><p>Please be sure to pick up your car after paying off the balance to prevent additional charges.</p></li>
  </ul>
  <br>
  <p>We are located at 4600 W Armitage Ave in Chicago, IL</p>
  <p>You can call us at (773) 555-1234</p>
</div>
{% endblock content %}

inventory/templates/messages.html
{% load static %}
<!-- Messages framework for notification bar at the top -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="{% static "inventory/dist/js/jquery.messagebar.min.js" %}"></script>

{% for message in messages %}
  <div class="messagebar messagebar-{% if message.tags %}{{ message.tags }}{% endif %}" id="message_{{ forloop.counter }}">
    <div class="container">
      {{ message }}
      <button type="button" class="close" data-dismiss="message">&times;</button>
    </div>
  </div>
{% endfor %}

<script>
  $(function() {
    $(".messagebar").messageBar({
      autoclose: 3000,
      slide: true,
    });
  });
</script>

inventory/templates/meta.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="T5 Towing Application" content="">
<meta name="Team 5" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">

inventory/templates/navbar.html
<!-- Navbar element for navigating the site -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  {% include "messages.html" %}
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">T5Towing</a>
    </div>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'profile' %}">Logged in as <strong>{{ user.username }}</strong></a></li>
        <li><button type="button" class="btn navbar-btn btn-info" name="logout" onclick="location.href='{% url 'logout' %}'">Log Out</button></li>
        {% else %}
        <li><a href="#">Logged in as <strong>Guest</strong></a></li>
        <li><button type="button" class="btn navbar-btn btn-primary" name="login" onclick="location.href='{% url 'login' %}'">Log In</button></li>
        <li>&nbsp;&nbsp;</li>
        <li><button type="button" class="btn navbar-btn btn-success" name="register" onclick="location.href='{% url 'registration' %}'">Register</button></li>
        {% endif %}
      </ul>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'inventory:search' %}">Search</a></li>
        <li><a href="{% url 'inventory:payment' %}">Make Payment</a></li>
        {% if user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">Management</li>
            <li><a href="{% url 'inventory:file_upload' %}">Import Data</a></li>
            <li><a href="{% url 'inventory:lotspace' %}">Lot Space Dashboard</a></li>
            <li><a href="{% url 'payment_summary' %}">Payment History</a></li>
            <li><a href="{% url 'inventory:checkin' %}">Vehicle Check-In</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Metrics</li>
            <li><a href="{% url 'metrics' %}">T5 Towing Metrics</a></li>
        {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>